#define src v0

DEFLABEL(HEAD):
INSN_COUNT1(seta,src);Lseta0:
TLseta_boolean_object:
TLseta_function:
TLseta_iterator:
TLseta_regexp:
TLseta_special:
TLseta_array:
TLseta_number_object:
TLseta_builtin:
TLseta_flonum:
TLseta_string_object:
TLseta_fixnum:
TLseta_simple_object:
TLseta_any:
TLseta_string:
{ // normal_builtin vmgen.newsynth.DecisionDiagram$Leaf@41d

  set_a(context, src);
}
#undef src

